### ISSUE TITLE
Chair Toggle Is Inverted

### ISSUE THREAD

**Issue by MistressPlague** [KortyBoi/ComponentToggle#1]
Noting I am running emmVRC and VRCAntiCrash, but the toggles within them do not fix this, yet disabling chairs in this mod makes chairs enabled.

**Comment by MistressPlague** [comment]
Yep, https://github.com/KortyBoi/ComponentToggle/blob/main/Utilities/Patches.cs#L23 the config bool should be the opposite condition, lul

**Comment by MintLily** [comment]
Oof, brain must've went brrr, I'll fix that once I get the chance.

**Comment by MistressPlague** [comment]
I dnspy hotfixed it in my modpack /shrug Btw better config boi: https://github.com/OFWModz/Better_ini
