### ISSUE TITLE
Post Processing on startup

### ISSUE THREAD

**Issue by PunDestrusct** [KortyBoi/ComponentToggle#2]
Every time I start the game I have to re-enable then disable post processing for it to be turned off

**Comment by MintLily** [comment]
What version of the mod are you running?

**Comment by PunDestrusct** [comment]
> What version of the mod are you running?

I'm currently running the latest version aka "the redo"

**Comment by MintLily** [comment]
Oh, i see what i missed. I'll fix it real quick

**Comment by MintLily** [comment]
Did that quick fix https://github.com/MintLily/ComponentToggle/releases/tag/2.0.1
